services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ecredit\ProcessManagerBundle\Service\ProcessManager:
    arguments:
      - '@Ecredit\ProcessManagerBundle\Service\Config'
      - '@doctrine.orm.default_entity_manager'

  Ecredit\ProcessManagerBundle\Command\ProcessManagerCommand:
    arguments:
      - '@Ecredit\ProcessManagerBundle\Service\ProcessManager'
    tags: ['console.command']

  Ecredit\ProcessManagerBundle\Command\ProcessManagerHealthCommand:
    arguments:
      - '@Ecredit\ProcessManagerBundle\Service\ProcessManager'
    tags: ['console.command']

  Ecredit\ProcessManagerBundle\Service\Config:
    arguments:
      - '%ecredit_process_manager.service.name%'
      - '%ecredit_process_manager.service.instance_name%'
      - '%ecredit_process_manager.commands%'

  Ecredit\ProcessManagerBundle\Controller\SupervisorController:
    class: Ecredit\ProcessManagerBundle\Controller\SupervisorController
    public: true